apollographql/federation-next

- .circleci/config.yml
Cargo doesnt support publishing multiple modules so we have to explicitly publish single module at a time.
Updating publish job to `apollo-federation` working directory
> specify working directory for publish

- .circleci/config.yml
This adds a CI job to ensure this repo can compile to wasm. Any change that doesn't work with wasm will then be flagged early.
> chore: add cargo build for wasm in ci

- src/error/mod.rs
- src/lib.rs
- src/link/database.rs
- src/link/mod.rs
- src/merge.rs
- src/subgraph/mod.rs
- src/subgraph/spec.rs
This PR is the second half of #85 , and fully updates `federation-next` to work with `apollo-compiler@1.0.0-beta.6`.
Some notes:
- This is mainly replacing `&str` with `Name`, and converting some functions to use `Result`s.
- The other notable changes are that types (e.g. `ObjectType`) need a `name` field now (making it consistent with the rest of the schema elements in `apollo-rs`), and some minor renames.
- Clippy warns that since `NodeStr` doesn't have `#[derive(PartialEq, Eq)]`, then we can't use `Name` in pattern-matching; I've worked around it with an enum and map for now.
- Consolidated a bit of the logic around converting subgraph names to enum values, with a `TODO` around doing what the JS codebase does.
- Unrelated, but I've been told we had some usages of `.eq()` in the Rust …
> Second half of updating `federation-next` to use `apollo-compiler@1.0.0-beta.6`

- src/link/federation_spec_definition.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/schema/position.rs
- src/schema/referencer.rs
This PR:
- Updates the `federation-next` schema wrapper to handle reserved names better. Specifically, we now:
- Error if we try to insert/remove elements containing fields/arguments/input fields/enum values that start with `__`.
- Note that built-in shadowing is still TODO/isn't implemented here, so accordingly we still ignore built-in types/directives as before.
- Allow fetching meta-fields for objects/interfaces/unions, via `apollo-rs`'s `Schema.type_field()` method.
- We track their GraphQL references appropriately, similar to the JS code.
- We also add some convenience functions to get child positions from parent positions, and update code to call them.
- Rearrange GraphQL reference insertion to occur after `Schema` element insertion instead of before, as we need the type to already …
> feat: Handle reserved names/meta-fields properly

- Cargo.toml
- src/link/argument.rs
- src/link/federation_spec_definition.rs
- src/query_graph/build_query_graph.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/query_graph/mod.rs
- src/schema/mod.rs
- src/schema/position.rs
This PR implements the intra-subgraph logic of federated query graph creation. That is, it implements the business logic that is performed for each individual subgraph when creating a federated query graph. The inter-subraph logic will be a separate PR, to keep PRs smaller. Tests will be added in follow-up PRs.
Some notes:
- Regarding porting, while the JS codebase creates a separate query graph for each subgraph and then copies its nodes/edges over to the federated one, the Rust code in this PR starts out with a single query graph (the federated one), and each builder adds its nodes/edges to that one. This allows us to avoid copying all the subgraph query graphs (and makes the porting/working with `petgraph` a bit easier).
- We introduce a few convenience functions for …
> feat: Intra-subgraph logic of federated query graph creation

- src/error/mod.rs
- src/link/spec_definition.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/schema/position.rs
- src/subgraph/mod.rs
- src/subgraph/spec.rs
`InvalidNameError` now contains the input string since compiler beta 7.
> Replace name conversion functions with error conversion impls

- Cargo.toml
- src/error/mod.rs
- src/link/federation_spec_definition.rs
- src/query_graph/build_query_graph.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/query_graph/field_set.rs
- src/query_graph/mod.rs
- src/schema/position.rs
This PR implements the inter-subgraph logic of federated query graph creation. That is, it implements the business logic for adding federated root nodes and cross-subgraph edges when creating a federated query graph. Note that this PR needs to use some functionality around operation processing eventually, but until that's ready, there are TODOs where the logic will be called. Tests will be added in follow-up PRs.
> feat: Inter-subgraph logic of federated query graph creation

- src/query_graph/build_query_graph.rs
- src/query_graph/mod.rs
- src/schema/position.rs
This PR ports the singular test in the JS codebase for query graph creation (most query planning tests are integration tests).
Some notes:
- You'll notice we introduce a new function called `build_query_graph()`; this is specifically for non-federated query graphs (used for the API schema during composition). We don't appear to have logic that directly tests federated query graphs in the JS codebase, but there's shared logic between non-federated and federated query graph creation, so this PR tests that shared logic at least.
- This PR is stacked on top of https://github.com/apollographql/federation-next/pull/94
> Port tests for query graph creation

- Cargo.toml
- src/database.rs
- src/error/mod.rs
- src/lib.rs
- src/link/database.rs
- src/merge.rs
- src/query_graph/build_query_graph.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/query_graph/field_set.rs
- src/query_graph/mod.rs
- src/schema/mod.rs
- src/schema/position.rs
- src/subgraph/mod.rs
- src/subgraph/spec.rs
- tests/snapshots/main__composition_tests__can_compose_supergraph.snap
- tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs.snap
- tests/snapshots/main__composition_tests__can_compose_with_descriptions-2.snap
- tests/snapshots/main__composition_tests__can_compose_with_descriptions.snap
- tests/snapshots/main__composition_tests__compose_removes_federation_directives.snap
- tests/subgraph/parse_expand_tests.rs
This PR (started by @SimonSapin and updated by me) updates `federation-next` to use `apollo-compiler@1.0.0-beta.10`.
> Update to apollo-compiler 1.0.0-beta.10

- src/lib.rs
- src/query_plan/mod.rs
- src/query_plan/operation.rs
- tests/main.rs
- tests/query_plan/mod.rs
- tests/query_plan/operation_optimization_tests.rs
- tests/query_plan/operation_tests.rs
- tests/query_plan/operation_validations_tests.rs
Initial version of operation normalization logic that auto-expands all fragments, deduplicates the fields and removes top level introspection fields.
related: #88
> feat: operation normalization for query planner

- src/query_plan/mod.rs
- src/query_plan/query_planner.rs
During standup, it was noted that having the struct for `QueryPlanner` would be helpful to unblock some operation processing work. This PR adds structs for `QueryPlanner` and its config.
Part of #30.
> feat: Add structs for `QueryPlanner` and its config

- Cargo.toml
It's not currently used anywhere. alternative to #20 :)
Or **should** we be using it somewhere?
> chore(deps): remove `env_logger`

- Cargo.toml
- src/query_plan/mod.rs
This PR adds Rust-centric versions of the data structures for query plan nodes (with an eye toward avoiding unnecessary serdes and using idiomatic Rust where possible).
Part of #30 .
> feat: Query Plan nodes

- src/query_graph/build_query_graph.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/query_plan/operation.rs
- src/query_plan/query_planner.rs
- src/schema/mod.rs
- tests/query_plan/operation_tests.rs
This PR makes the following adjustments:
-  Changes`ValidFederationSchema` to use `Arc`, and specify equality via `Arc.ptr_eq()` (as the JS code defines schemas as equal if they reference the same object, and in our case post-validation the `FederationSchema` won't change). This should avoid having to custom-define equality in some places that previously used `Arc<ValidFederationSchema>`.
- Renames the selection types `NormalizedField`, `NormalizedFragmentSpread`, and `NormalizedInlineFragment` to additionally have the suffix `Selection` (e.g. `NormalizedFieldSelection`).
- Pulls the non-selection-set data out of `NormalizedFieldSelection` and `NormalizedInlineFragmentSelection` into `NormalizedField` and `NormalizedInlineFragment` (this mimics the JS's naming convention). These will be …
> feat: Adjust operation types

- src/link/database.rs
- src/subgraph/mod.rs
Clippy wants you to use `.first()` over `.get(0)`. I don't like this rule to be honest, in the places where we use it the first-ness of 0 is not meaningful. We could disable it but its not that important. This gets CI passing again
> chore: Apply Clippy suggestions from Rust 1.75

- src/lib.rs
- src/link/federation_spec_definition.rs
- src/link/join_spec_definition.rs
- src/link/link_spec_definition.rs
- src/link/mod.rs
- src/link/spec_definition.rs
- src/merge.rs
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/query_plan/operation.rs
- src/schema/mod.rs
- src/subgraph/mod.rs
This PR is a grab-bag of a few things I ran into while getting into API schema validation. I won't be able to finish that before holiday break so posting the generic changes first.
- Change uses of `directives.iter().any()` to `directives.has()`, which is a little easier: [`DirectiveList::has`](https://docs.rs/apollo-compiler/1.0.0-beta.11/apollo_compiler/ast/struct.DirectiveList.html#method.has)
- Return an `Iterator` instead of a `Vec` from `get_types()`, the user can still decide to `collect()` it into a vec if needed. Also adds a parallel `get_directive_definitions()`.
- Return `Option<&LinksMetadata>` instead of `&Option<LinksMetadata>`-- an option containing a reference is a much more useful type than a reference to an option. You basically always want to prefer an `Option<&T>` if …
> chore: a few minor fixes / improvements

- Cargo.toml
- src/link/argument.rs
- src/merge.rs
Just some papercut fixes and a way to lookup schema coordinates, which is mostly intended for tests:
```rust
assert!(coord!(Type.field).lookup_field(&schema).is_ok());
```
> deps: update apollo-compiler to 1.0.0-beta.12

- src/link/database.rs
- src/link/spec.rs
Fixes two compatibility issues with our `@link` parsing found in customer schemas:
* explicit import of a root directive `@link(url: "https://example.com/myDirective", import: ["@myDirective"])` was treated as a conflict between the explicit and implicit import of `@myDirective`, changing it to only be a conflict if the explicit and implicit import came from *different* `@link`s
* linking a spec with an invalid GraphQL name, `@link(url: "https://example.com/spec-name", import: ["@directive"])`. According to the `@link` spec names must be valid GraphQL but the federation JS code does not check this and schemas exist in the wild that do this. namespacing doesn’t work with invalid names, but explicitly importing elements does, so I’m changing the Rust code to accept invalid names as well …
> fix: @link compatibility with JS federation

- src/query_plan/operation.rs
- src/schema/position.rs
- tests/api_schema.rs
Fixes deprecation warnings:
https://app.circleci.com/pipelines/github/apollographql/federation-next/520/workflows/b38dcd16-5efe-458b-811d-f60eb757549c/jobs/2405?invite=true#step-107-4864_166
This deprecation is push towards an explicit choice between:
* `shift_remove`, which preserves the relative ordering of remaining items but takes O(n) time like `Vec::remove`
* `swap_remove`, which is O(1) but moves the previously-last item to the emptied slot.
I conservatively went with `shift_remove` everywhere. Are there cases where we don’t care about preserving ordering?
> `Index{Map,Set}::remove` → `shift_remove`

- examples/api_schema.rs
- src/api_schema.rs
- src/lib.rs
- tests/api_schema.rs
- tests/composition_tests.rs
Whether `@defer` or `@stream` should be exposed depends on the capabilities and configuration of the supergraph router. This option adds the definitions to the API schema if requested.
> feat: add options to insert `@defer`, `@stream` in API schema

- src/query_graph/field_set.rs
- src/query_plan/operation.rs
`normalize_operation` now returns `NormalizedOperation`.
By default, when normalizing selection sets, we auto expand and inline fragment spreads. In order to be able to rebase fragments we need to normalize their selection sets without inlining other fragments. Updated method to accept explicit `FragmentSpreadNormalizationOption` enum option to indicate whether to inline spreads or preserve them (it is the same logic except for handling fragment spreads).
> [operation normalization] return NormalizedOperation and normalize Fragment

- src/link/argument.rs
- src/link/graphql_definition.rs
- src/query_graph/condition_resolver.rs
- src/query_graph/graph_path.rs
- src/query_graph/mod.rs
- src/query_graph/path_tree.rs
- src/query_plan/operation.rs
- src/schema/position.rs
> Query Graph Traversal: Part 2

- Cargo.toml
Nothing particularly interesting for fed-next in this release. But after upgrading & releasing fed-next we can start testing API schema in router.
> chore(deps): update apollo-compiler to beta.13

- Cargo.toml
When we push a vX.Y.Z tag, it automatically gets published, right? 😇 
This is to release the apollo-compiler upgrade and the API schema implementation.
> Prep 0.0.6 release

- src/api_schema.rs
- tests/api_schema.rs
There was a rather silly mistake in the `@defer` definition: it applies to fragment spreads, but I copy-pasted wrong and made it apply to fields instead. That's fixed now.
I also removed the doc comments from the definitions. The JS code did not add them and having them messes up the comparison between JS and Rust results in the router. If it's any use to have it, we can re-add it later when the JS implementation is gone.
> fix: more compatible definitions added by `include_{defer,stream}`

- CHANGELOG.md
- Cargo.toml
The fix to API schema directives supports the `experimental_api_schema_generation_mode: both` setting in the router.
> Prepare 0.0.7 release

- src/query_plan/operation.rs
apollo-rs doesn't come with `@defer` defined by default, because it depends on server-side implementer support. We have to provide our own definition in tests that test `@defer`.
These tests are mostly ported from JS, but they don't make sense. You can't use `@defer` on a field, only on fragment spreads. In this PR I change the uses to inline fragments wrapping each field, which should have the same effect.
In the `merge_fragments` test I remove `@defer` entirely, I don't *think* it adds much there, since the test is more interesting if it checks that nested fields are actually merged correctly.
Closes #213
> Enable operation normalization tests using defer

- src/link/database.rs
- src/link/mod.rs
- tests/api_schema.rs
This is for backward compatibility with existing supergraphs, bolting `@core` support onto the `@link` reading. It does not do anything to support fed v1 supergraphs.
While `@core` is not used in new graphs today, it is supported by the JS code, and we have a lot of tests throughout our systems that rely on using `@core` with fed v2.
Additionally, because the implementation of API schema generation is the same between fed v1 and fed v2, supporting `@core` will let us land it in the router *without* a fallback to JS for fed v1 supergraphs.
All new code that supports `@core` mentions `@core` literally in a comment so we can rip it out easily when we migrate over customers and our tests in the router.
> feat: support legacy `@core` link syntax

- CHANGELOG.md
- Cargo.toml
For API schema in router 🤞🏻 
- Support legacy `@core` link syntax, by [goto-bus-stop] in [pull/224]  
This is not meant to be a long term feature, `@core()` is not intended
to be supported in most of the codebase.
- `@link(url: String!)` argument is non-null, by [SimonSapin] in [pull/220]
- Enable operation normalization tests using `@defer`, by [goto-bus-stop] in [pull/224]
[SimonSapin]: https://github.com/SimonSapin
[goto-bus-stop]: https://github.com/goto-bus-stop
[pull/220]: https://github.com/apollographql/federation-next/pull/220
[pull/223]: https://github.com/apollographql/federation-next/pull/223
[pull/224]: https://github.com/apollographql/federation-next/pull/224
> Prepare 0.0.8 release

- src/query_plan/mod.rs
- src/query_plan/query_planner.rs
Just call into the parts that already exist (operation normalisation)
This is intended to be a stub to start experimenting with router integration (like getting all the types in order).
> [Query Planner] add stub implementation for QueryPlanner::build_query_plan

- CHANGELOG.md
- Cargo.toml
Just to get new apollo-compiler into router
- Continued work on core query planning implementation, by [goto-bus-stop] in [pull/229]
- Update `apollo-compiler`, by [goto-bus-stop] in [pull/230]
[goto-bus-stop]: https://github.com/goto-bus-stop
[pull/229]: https://github.com/apollographql/federation-next/pull/229
[pull/230]: https://github.com/apollographql/federation-next/pull/230
> Prepare 0.0.9 release

- src/lib.rs
Example previous message:
> The supergraph schema failed to produce a valid API schema: Invalid supergraph: uses unsupported join spec version 0.1, 0.2, 0.3 (supported versions: 0.4)
~~Also add https://specs.apollo.dev/join/v0.4 to the list of supported version. Are more changes needed to properly support it? This version seems to exist in https://github.com/apollographql/federation/pull/2907, but it’s not listed on https://specs.apollo.dev/ and https://specs.apollo.dev/join/v0.4 itself is a 404 error as of this writing.~~
> Fix backwards error message for unsupported join spec version

- src/lib.rs
Thread-safe meaning implementing the `Send` and `Sync` traits. They already are, but with this PR we won’t regress accidentally.
The consenquence is that we should keep using `Arc` over `Rc`, `Mutex` or `RwLock` over `Cell` or `RefCell`, etc.
> Add static assertions that Supergraph and QueryPlanner are thread-safe

- src/query_graph/graph_path.rs
This PR addresses Jira ticket FED-28.
After verifying that the `PartialEq` implementation on `Arc` does the desired short-circuiting and the derived behavior matches what is expected in the JS code, the stubs for the manual implementation of `PartialEq` and `Hash` were replaced with derived implementations.
> Derive PartialEq and Hash for OpGraphPathContext

- src/schema/position.rs
- src/schema/referencer.rs
Just a little cleanup to make this read nicer...
Since `Name`s implicitly deref to `&str`, hash the same, and can do equality comparisons, we can use the concrete type `&str` instead of specifying multiple generic trait bounds.
> Remove unnecessary generics

- .cargo/config
- Cargo.toml
- README.md
- cli/Cargo.toml
- cli/src/main.rs
Example usage: `cargo cli api ../router/examples/graphql/supergraph.graphql`
This executable is intended to be the successor of https://github.com/apollographql/composer-tool. Initially it has a single `api` subcommand that converts a supergraph schema to its corresponding API schema. (Error handling can be improved.)
The CLI is a separate crate so that the library crate does not need to depend on `clap`. See https://blog.axo.dev/2024/03/its-a-lib-and-a-bin
> Add skeleton CLI tool

- src/link/graphql_definition.rs
- src/query_graph/graph_path.rs
This PR addresses Jira ticket FED-20.
Display for `OpGraphPath` has been implemented by representing the path with an array of edges. The edges are represented with their Debug impl, which can be changed. Currently, this implementation is the same as the debug impl of the edges.
Since the `edges` are `Option<EdgeIndex>>`, I am unsure how to represent the `None` case or if that was a concern at all. If there is a preferred way to represent the edges, I'll gladly change it.
> impl Display for OpGraphPath

- cli/src/main.rs
- src/query_graph/mod.rs
- src/query_graph/output.rs
added query_graph::output::to_dot function
- outputs query graphs in the GraphViz Dot format
- supports both federated schemas and non-federated ones
> Ported the GraphViz `dot`-format output for query graphs

- Cargo.toml
- src/query_graph/extract_subgraphs_from_supergraph.rs
- src/schema/mod.rs
This PR addresses Jira ticket FED-53.
This method, ported from JS, appends additional information to error messages when attempting to extract subgraphs from a supergraph. Users can also set the environment variable `APOLLO_FEDERATION_DEBUG_SUBGRAPHS` to have the schema written to a file.
> Ported maybe_dump_subgraph_schema from JS

- Cargo.toml
Adds a validation rule that's especially useful for synthetic schemas (types must have at least 1 field) and a serialization feature for #244.
> deps: update apollo-compiler to 1.0.0-beta.15

- Cargo.toml
- cli/Cargo.toml
- cli/src/main.rs
- src/query_plan/display.rs
- src/query_plan/mod.rs
… and add a `cargo cli plan <query.graphql> <schema.graphql>` CLI subcommand. For now it panics because query planing logic (creating the plan to display) has not yet been entirely ported.
These impls will also be used:
* In snapshot tests to be ported from `buildQueryPlan.test.ts` and `buildPlan*.test.ts`
* In the Router `expose_query_plan` plugin
This new code is **untested**. However, compiler exhaustiveness checks show that it’s mostly there. When snapshot tests start exercising it we can adjust it as needed.
> Port queryPlanSerializer as Display impls

- CHANGELOG.md
- Cargo.toml
To release `join/v0.4` for API schema in Router, and a bunch of stuff for QP in Router.
- Query plan changes for initial router integration, by [SimonSapin] in [pull/240]
- Mark join/v0.4 spec as supported for non-query planning purpose, by [SimonSapin] in [pull/233], [pull/237]
- Continued work on core query planning implementation, by [duckki], [SimonSapin], [TylerBloom]
- Update `apollo-compiler`, by [goto-bus-stop] in [pull/253]
[duckki]: https://github.com/duckki
[goto-bus-stop]: https://github.com/goto-bus-stop
[SimonSapin]: https://github.com/SimonSapin
[TylerBloom]: https://github.com/TylerBloom
[pull/233]: https://github.com/apollographql/federation-next/pull/233
[pull/237]: https://github.com/apollographql/federation-next/pull/237
[pull/240]: …
> Prepare 0.0.10 release

- src/error/mod.rs
- src/query_graph/field_set.rs
Added a check for the absence of aliases in field set directive arguments.
Federation-next uses the apollo-compiler to parse the field-set argument string as GraphQL code. Similarly, the JS federation uses graphql-js to parse it. Both GraphQL parsers allow aliases in it, while federation does not allow it. That’s why the JS federation looks for aliases after parsing it. I think it makes sense to do the same thing in the Rust implementation so we don’t need to make changes in the apollo-compiler itself.
I did not attempt to make our error message to match exactly with the JS implementation. First of all, it's not necessary for unblocking QP work, while improving error messages will require further refactoring elsewhere. We might want to revisit the whole error message business later when …
> parse_field_set: forbid aliases

- src/query_graph/mod.rs
- src/query_plan/query_planner.rs
This is to be used in Router integration
> Expose subgraphs schemas to crate consumers

- CHANGELOG.md
- Cargo.toml
- apollo-compiler update to release rust-only validation in router;
- #257 to support QP integration in router.
> Prepare 0.0.11 release

- src/query_graph/field_set.rs
- src/query_plan/fetch_dependency_graph.rs
- src/query_plan/fetch_dependency_graph_processor.rs
- src/query_plan/operation.rs
- src/schema/mod.rs
- src/schema/position.rs
Implements logic to rebase fragments/selections on a given schema.
This is a big PR that introduces some to the underlying selection set data structures - `NormalizedFragmentSpreadSelection` now includes a selection set from corresponding fragment definition. This now matches how they were represented in both JS and RS implementations.
Some differences between implementations:
* spread selection does not store `NamedFragments` in RS implementation and instead we just pass those over whenever needed
* `NamedFragments` are using `IndexMap` to store `NormalizedFragments` and is initialized in their dependency order (i.e. if fragment `A` depends on `B` then `B` will be inserted first). Since they are initialized in order, we no longer need to apply the `mapInDependencyOrder` for other …
> operation rebase_on logic

- src/error/mod.rs
- src/query_graph/build_query_graph.rs
- src/query_graph/mod.rs
- src/query_plan/display.rs
- src/query_plan/fetch_dependency_graph.rs
- src/query_plan/fetch_dependency_graph_processor.rs
- src/query_plan/mod.rs
- src/query_plan/operation.rs
- src/query_plan/query_planner.rs
- src/query_plan/query_planning_traversal.rs
The scope of this PR is to implement `build_query_plan` and the top-level functions for the *simple* planning paths (no defer, and no mutations). After this PR, a call to `build_query_plan` should ideally hit a `todo!()` somewhere deeper inside the project, not at the top level. Some lifetime changes are required to existing code which is where most of the diff comes from.
---
`planner.build_query_plan()` can now run until we get to the processor stage (where the fetch dependency graph cost is calculated). I stopped there because processing is a big chunk of code that looks like it should be part of FED-62.
Notes on the changes to existing code:
- Because we aren't working with owned selection sets in selection set merging in mutation operations, but with `Arc`s, I changed the existing …
> Implementation of `QueryPlanner::build_query_plan`

- src/query_graph/condition_resolver.rs
- src/query_graph/graph_path.rs
- src/query_graph/mod.rs
- src/query_plan/fetch_dependency_graph_processor.rs
- src/query_plan/operation.rs
- src/query_plan/query_planner.rs
- src/query_plan/query_planning_traversal.rs
I was tasked to implement the `CachingConditionResolver`, which is used in `QueryPlanningTraversal`. 
The TypeScript version of `QueryPlanningTraversal` has a field `conditionResolver`, which is a closure that captures `this` (QueryPlanningTraversal) as mutable reference and calls `this.resolveConditionPlan`. The problem is that there is a cyclic reference structure: `QueryPlanningTraversal` -owns-> `conditionResolver` -captures-> `QueryPlanningTraversal`. 
In Rust, `CachingConditionResolver` can't mutably reference `QueryPlanningTraversal`, since we want `QueryPlanningTraversal`  to hold the `CachingConditionResolver` itself. (Not considering smart pointers or unsafe references)
I decided not to implement `CachingConditionResolver`. Instead, I made `QueryPlanningTraversal` to implement …
> FED-46: Implemented `ConditionResolver` trait for `QueryPlanningTraversal`

- src/query_plan/operation.rs
- src/query_plan/query_planning_traversal.rs
Along with `NormalizedSelection::has_defer()`, additionally implements:
* `NormalizedFieldSelection::has_defer()`
* `NormalizedFragment::has_defer()` (for `NormalizedOperation::without_defer()` implementation)
* `NormalizedFragmentSpreadSelection::has_defer()`
* `NormalizedInlineFragmentSelection::has_defer()`
* `NormalizedSelectionSet::has_defer` (for `NormalizedOperation::without_defer()` implementation)
> implement NormalizedSelection::has_defer()

- Cargo.toml
- src/query_graph/graph_path.rs
- src/query_graph/mod.rs
- src/query_plan/conditions.rs
- src/query_plan/fetch_dependency_graph.rs
- src/query_plan/fetch_dependency_graph_processor.rs
- src/query_plan/query_planner.rs
- src/query_plan/query_planning_traversal.rs
This ports the `process*` functions from FetchDependencyGraph. All the process functions are renamed from `process*Group*` to `process*Node*`. Internal types like `DeferredGroup` are renamed to `DeferredNode`.
I also implemented `create_initial_options` which lets us actually get to a `todo!()` again instead of early returning an empty plan.
`VariableConditions` had a documented invariant that it's never empty, but the type's API didn't uphold the invariant and allowed outside access to internals. Now the `conditions` module and the public API uphold this invariant.
> Implement FetchDependencyGraph processor traversal

- src/sources/connect/spec/directives.rs
- src/sources/connect/spec/schema.rs
We use a list of `{name:, value?:, as?:}` object because we can't use an object — header names aren't valid GraphQL object keys. But it really is a map, especially so we can easily merge the `@connect` headers into the `@source` headers, overriding by name. Also, the `value` field can be a list of values.
> use a map for headers

- src/query_graph/graph_path.rs
- src/query_graph/mod.rs
- src/query_plan/query_planning_traversal.rs
This PR ports `advancePathWithNonCollectingAndTypePreservingTransitions()` and its downstream methods.
There is one TODO introduced about populating dead-end information, but it's only necessary for composition (tracked in FED-173).
> Graph Traversal: Handle non-collecting type-preserving edges

- src/query_graph/graph_path.rs
The derived Debug impl for `GraphPath` included the whole query graph, which made it untenable to read. This patch removes that field from the Debug representation.
OpGraphPaths have a terse string representation. In other structures that contain OpGraphPaths, I think the terse representation is preferable. This adds Debug impls to use the terse representation in those cases.
This has no usage sites, but it's handy for println debugging.
> Add/improve some Debug impls

- .circleci/config.yml
macos intel configs are being removed by circleci.
I copied the M1 config from router.
> ci: use macos M1 machines

- src/error/mod.rs
We are using internal errors *a ton* inside the query planner, and while `ErrorCode::definition` is not yet used, I don't want to accidentally have us run into a panic with error codes. There is a follow up ticket for documenting this when we deal with composition later on - https://apollographql.atlassian.net/browse/FED-190
> Add a temporary error code definition for internal errors

- src/query_graph/mod.rs
This is used in `OpGraphPath::advance_with_operation_element()`.
Original in JS: https://github.com/apollographql/federation/blob/bbf83946800d0e6f83307e1941cd7052f8a3c38d/query-graphs-js/src/graphPath.ts#L2213-L2224
> Port has_an_implementation_with_provides()

- src/lib.rs
- src/query_graph/graph_path.rs
- src/query_graph/mod.rs
- src/schema/position.rs
This PR addresses FED-33 and is a port of [`anImplementationIsEntityWithFieldShareable`](https://github.com/apollographql/federation/blob/main/query-graphs-js/src/graphPath.ts#L2279).
There are a number of differences between how the JS code and Rust code represent query graphs, graph paths, nodes, and edges. The original source code is linked above. I tried to keep everything one-to-one, but there is one thing that seems to not be needed: the `baseType` function. This is called a few times in the original JS code, but I was unable to find a translation for it.
> Ported anImplementationIsEntityWithFieldShareable from JS

- src/link/graphql_definition.rs
- src/query_graph/graph_path.rs
- src/query_plan/fetch_dependency_graph.rs
- src/query_plan/operation.rs
- src/schema/position.rs
Implemented the following:
- `FetchInputs::add/add_all` methods
- `wrap_input_selections` and `create_fetch_initial_path` functions
-  `compute_input_rewrites_on_key_fetch` function
- And some various helper methods.
https://apollographql.atlassian.net/browse/FED-37
> FED-37: Port FetchInputs::add from GroupInputs.add

- src/link/graphql_definition.rs
- src/link/mod.rs
- src/query_graph/graph_path.rs
- src/query_plan/fetch_dependency_graph.rs
- src/query_plan/fetch_dependency_graph_processor.rs
Implemented `extract_defer_from_operation` function.
Even though most of its functionality won't be used until `@defer` is actually implemented, it's called from `compute_nodes_for_op_path_element` and we would've needed some implementation anyways. So, I ported all of it.
> FED-189: port extractDeferFromOperation
